<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>DashX360</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>false</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <DebugType Condition="'$(Configuration)' == 'Release'">embedded</DebugType>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
    <DebugType Condition="'$(PublicRelease)' == 'true'">none</DebugType>
    <PublishDocumentationFiles Condition="'$(PublicRelease)' == 'true'">false</PublishDocumentationFiles>
    <DefaultItemExcludes>$(DefaultItemExcludes);Build\**;bin\**;obj\**;UserData\**;Logs\**</DefaultItemExcludes>
    <ApplicationIcon>Assets\Misc\256x256.ico</ApplicationIcon>
    <RootNamespace />
    <Product>DashX360</Product>
    <Version>1.3.0</Version>
    <InformationalVersion>v1.3.0-blades-public</InformationalVersion>
    <AssemblyVersion>1.3.0.0</AssemblyVersion>
    <FileVersion>1.3.0.0</FileVersion>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="XboxMetroLauncher\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="XboxMetroLauncher\App.xaml" />
    <Page Include="XboxMetroLauncher\MainWindow.xaml" />
    <Page Include="XboxMetroLauncher\XboxMetroLauncher.Themes\*.xaml" />
    <Page Include="controls\*.xaml" />
    <Page Include="themes\*.xaml" />
    <Page Include="views\*.xaml" />
    <Page Include="views\tabs\*.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.Collections.ObjectModel" />
    <Using Include="System.Globalization" />
    <Using Include="System.IO" />
    <Using Include="System.Linq" />
    <Using Include="System.Threading" />
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Data\*.json" Condition="'$(PublicRelease)' != 'true'" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="Assets\**\*" Exclude="Assets\References\*layout.*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Remove="Assets\Custom Files\**\*;Assets\GameArt\Steam\**\*" Condition="'$(PublicRelease)' == 'true'" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3124.44" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="SharpDX.DirectInput" Version="4.2.0" />
  </ItemGroup>

</Project>
